config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  # root to: "home#index"
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'settings' }

  root to: 'application#home'

  get '/home', to: 'application#home', as: 'home'
  get '/secret', to: 'application#secret', as: 'secret'
  get '/about', to: 'application#about', as: 'about'
  get '/contact', to: 'application#contact', as: 'contact'

  resources :horses do
    resources :notes
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/meeting.rb
class Meeting < ApplicationRecord
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:name, :description, :start_time, :end_time)
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_for @meeting do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2> "#{pluralize(@meeting.errors.count, "error")} prohibited this meeting from being saved:"</h2>
      <ul>
        <% @meeting.errors.full_messages.each do |message| %>
          <li> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :start_time %>
    <div class="input-group date form_datetime" data-date="<%= @meeting.start_time.try(:strftime, "%F %T") %>" data-date-format = "YYYY-MM-DD hh:mm:ss" data-link-field="meeting_start_time">
      <input class="form-control" size="16" type="text" value="<%= @meeting.start_time.try(:strftime, "%F %T") %>" readonly="" />

      <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
    </div>
  <%= f.hidden_field :start_time %>

  </div>
  <div class="form-group">
    <%= f.label :end_time %>
    <div class="input-group date form_datetime" data-date="<%= @meeting.end_time.try(:strftime, "%F %T") %>" data-date-format = "YYYY-MM-DD hh:mm:ss" data-link-field="meeting_end_time">
      <input class="form-control" size="16" type="text" value="<%= @meeting.end_time.try(:strftime, "%F %T") %>" readonly="" />

      <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
    </div>
    <%= f.hidden_field :end_time %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
  <script type="text/javascript">
      $(".form_datetime").datetimepicker({
           format: 'yyyy-mm-dd hh:ii:ss p',
           showMeridian: true,
           autoclose: true,
           weekStart: true,
           todayBtn: true,
           todayHighlight: true
      });

  </script>
<% end %>

app/views/meetings/edit.html.slim
h1 Editing meeting

== render 'form'

=> link_to 'Show', @meeting
'|
=< link_to 'Back', meetings_path

app/views/meetings/index.html.slim
h1 Listing meetings

table
  thead
    tr
      th Name
      th Description
      th Start time
      th End time
      th
      th
      th

  tbody
    - @meetings.each do |meeting|
      tr
        td = meeting.name
        td = meeting.description
        td = meeting.start_time
        td = meeting.end_time
        td = link_to 'Show', meeting
        td = link_to 'Edit', edit_meeting_path(meeting)
        td = link_to 'Destroy', meeting, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Meeting', new_meeting_path

app/views/meetings/new.html.slim
h1 New meeting

== render 'form'

= link_to 'Back', meetings_path

app/views/meetings/show.html.slim
p#notice = notice

p
  strong Name:
  = @meeting.name
p
  strong Description:
  = @meeting.description
p
  strong Start time:
  = @meeting.start_time
p
  strong End time:
  = @meeting.end_time

=> link_to 'Edit', edit_meeting_path(@meeting)
'|
=< link_to 'Back', meetings_path