config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  # root to: "home#index"
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'settings' }

  root to: 'application#home'

  get '/home', to: 'application#home', as: 'home'
  get '/secret', to: 'application#secret', as: 'secret'
  get '/about', to: 'application#about', as: 'about'
  get '/contact', to: 'application#contact', as: 'contact'

  resources :horses do
    resources :notes
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:home, :about, :contact]

  def home
    @meetings = Meeting.all
  end

  def about
  end

  def contact
  end

  def secret
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/about.html.slim
= content_for :title do
  = 'About'

.text-center
  h1 About
  p.text-success about details goes here

app/views/application/contact.html.slim
= content_for :title do
  = 'Contact'

.text-center
  h1 Contact
  p.text-success contact details goes here

app/views/application/home.html.erb
<div class="text-center">
  <%= link_to 'Create Event', new_meeting_path %>
  <%= month_calendar events: @meetings do |date, meetings| %>
    <%= date.day %>

    <% meetings.each do |meeting| %>
      <div>
        <%= link_to meeting.name, meeting_path(meeting) %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/application/secret.html.slim
= content_for :title do
  = 'Secret'

.text-center
  h1 Secret
  p.text-success only logged in user can access this page